# Generated by Django 5.0.6 on 2024-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=30)),
                ('emailsub', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
