# Generated by Django 5.0.6 on 2024-05-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
